module.exports = {
  content: ['storyblok/**/*.{vue,js}', 'pages/**/*.vue'],
  safelist: [
    'bg-primary-highlight',
    'bg-highlight-1',
    'bg-highlight-2',
    'bg-highlight-3',
    'bg-primary-background',
    'bg-background-1',
    'bg-background-2',
    'bg-background-3',
    'bg-background-4',
    'bg-background-5',
    'bg-background-6',
    'bg-background-7',
    'bg-background-8',
    'bg-background-9',
    'bg-background-10',
    'bg-primary-dark',
    'bg-white',
    'hover:bg-primary-highlight',
    'hover:bg-highlight-1',
    'hover:bg-highlight-2',
    'hover:bg-highlight-3',
    'hover:bg-primary-background',
    'hover:bg-background-1',
    'hover:bg-background-2',
    'hover:bg-background-3',
    'hover:bg-background-4',
    'hover:bg-background-5',
    'hover:bg-background-6',
    'hover:bg-background-7',
    'hover:bg-background-8',
    'hover:bg-background-9',
    'hover:bg-background-10',
    'hover:bg-primary-dark',
    'hover:bg-white',
    'text-primary-highlight',
    'text-highlight-1',
    'text-highlight-2',
    'text-highlight-3',
    'text-primary-background',
    'text-background-1',
    'text-background-2',
    'text-background-3',
    'text-background-4',
    'text-background-5',
    'text-background-6',
    'text-background-7',
    'text-background-8',
    'text-background-9',
    'text-primary-dark',
    'text-white',
    'hover:text-primary-highlight',
    'hover:text-highlight-1',
    'hover:text-highlight-2',
    'hover:text-highlight-3',
    'hover:text-primary-background',
    'hover:text-background-1',
    'hover:text-background-2',
    'hover:text-background-3',
    'hover:text-background-4',
    'hover:text-background-5',
    'hover:text-background-6',
    'hover:text-background-7',
    'hover:text-background-8',
    'hover:text-background-9',
    'hover:text-primary-dark',
    'hover:text-white',
    'border-primary-highlight',
    'border-highlight-1',
    'border-highlight-2',
    'border-highlight-3',
    'border-primary-background',
    'border-background-1',
    'border-background-2',
    'border-background-3',
    'border-background-4',
    'border-background-5',
    'border-background-6',
    'border-background-7',
    'border-background-8',
    'border-background-9',
    'border-primary-dark',
    'border-white',
    'fill-primary-highlight',
    'fill-highlight-1',
    'fill-highlight-2',
    'fill-highlight-3',
    'fill-primary-background',
    'fill-background-1',
    'fill-background-2',
    'fill-background-3',
    'fill-background-4',
    'fill-background-5',
    'fill-background-6',
    'fill-background-7',
    'fill-background-8',
    'fill-background-9',
    'fill-primary-dark',
    'fill-white',
    'items-start',
    'items-center',
    'items-end',
    'text-center',
    'text-left',
  ],
  theme: {
    container: {
      center: true,
      padding: {
        DEFAULT: '1rem',
        lg: '2rem',
      },
    },
    fontFamily: {
      display: 'var(--font-family-display)',
      body: 'var(--font-family-body)',
    },
    borderRadius: {
      'none': '0',
      'sm': 'var(--rounded_sm)',
      'DEFAULT': 'var(--rounded_default)',
      'md': 'var(--rounded_md)',
      'lg': 'var(--rounded_lg)',
      'xl': 'var(--rounded_xl)',
      '2xl': 'var(--rounded_2xl)',
      '3xl': 'var(--rounded_3xl)',
      'full': 'var(--rounded_full)',
    },
    extend: {
      colors: {
        'primary-highlight': 'var(--primary-highlight)',
        'highlight-1': 'var(--highlight-1)',
        'highlight-2': 'var(--highlight-2)',
        'highlight-3': 'var(--highlight-3)',
        'primary-background': 'var(--primary-background)',
        'background-1': 'var(--background-1)',
        'background-2': 'var(--background-2)',
        'background-3': 'var(--background-3)',
        'background-4': 'var(--background-4)',
        'background-5': 'var(--background-5)',
        'background-6': 'var(--background-6)',
        'background-7': 'var(--background-7)',
        'background-8': 'var(--background-8)',
        'background-9': 'var(--background-9)',
        'primary-dark': 'var(--primary-dark)',
      },
      typography: {
        DEFAULT: {
          css: {
            lineHeight: '1.625',
          },
        },
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
